dist: trusty

language: node_js

node_js:
  - node
  - lts/*

addons:
  sonarcloud:
    organization: diplomatiq
    token:
      secure: OuO5PTGVrqinpQk1pj/WoivbcFglhS56Hxddzh6r2zZJ4DfTESWJhFS9b4SD7bwPoNLEDDrjMM5cdNy+S3j0pR1g46iNWDLbhBsYf4+l006QEIajjf3vt5CkkREhLtA4EMiHIgW68sHUKKoq4vdUlOQ+L0hvpScahtNUkP48uUvKJpKnGvaL/hcMzYz2TAv3/jvd8oYNAY0k0G5w3kCxwLZfJkhhSDtZEX5tEQ5ARBu9A24X9Xsza3JegrHESzLIto2XMLfJcy9m34I5OfXnVYEyiydO5bOxW00bCn7o41HNLhlx7vPD+JatYvwEHbVdDb9QOdHTHyXqAO00JbNsHyslVhTLcVFWNGvltDueY/pmjluxR40YCBJbEOz3WE4V+LsSjM71vFWj/xZRVBWGSbPVNDYL+3+4YfSSvdxFtowDFP3PEjXb9GBWWCoiSmyqZjMbkneCS7P8W1oLVJCuqDgVmWSsRSiVpS0zAhcbe+LOV4WLIUuAMrIMUpx091BBLNEA9V4O0ML080enuyrwhNH7/D626GjfTbTEntPF5h6P2gtV3/1yp8bOJXpJQkHjVP8kedFSZJBDdcwvCsc5E9WsTRrYjMs2bpk8MqwV5D54yzVwnkXtrzOjB4jPvF2oQwUIGC1kgIOIKn52IUGUnagDgO4meUPS+Y8bAcpSZiM=

install: npm ci

script:
  - commitlint-travis
  - npm run build-and-test-everything
  - sonar-scanner
