version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    default_assignees:
      - "luczsoma"
    default_labels:
      - "dependencies"
      - "dependabot"
    commit_message:
      prefix: "chore"
